name: UltraCaptureTheWool
main: io.github.Leonardo0013YT.UltraCTW.UltraCTW
version: 3.0
author: Leonardo0013YT
description: UltraCTW edited by FrxnkLxrd
softdepend: [ PlaceholderAPI ]
depend: [ ProtocolLib, WorldEdit, FastAsyncWorldEdit ]
commands:
  stats:
  ctws:
    aliases: [ ctwadmin ]
  ctw:
  leave:
    aliases: [ salir ]
  join:
    aliases: [ jugar ]
  kiteditor:
  savekit:
  resetkit:
  globaltoggle:
    aliases: [ gl, g ]