# Removed some things that are not used, in the config and in the plugin code.
# If you need help you can consult the discord server: https://discord.com/invite/3RRWVTGveD
debugMode: false
addons:
  placeholdersAPI: true
  NametagEdit: true
mainLobby: null
mobGriefing: false
progressBarAmount: 10
excluideDefKits: true
kitLevelsOrder: true
lobbyScoreboard: true
statsCMD: true
updatePlayersPlaceholder: 5
breakMap:
  enabled: true
  totalBreak: true
  bypass:
    - WEB
    - GOLD_BLOCK
    - IRON_BLOCK
redPanelInLocked: true
redPanel:
  material: STAINED_GLASS_PANE
  data: 14
gameDefaults:
  autoJoinFinish: false
  hunger: false
  instaKillOnVoid: true
  maxMultiplier: 5
  starting: 30
  timeToKill: 30
  limitOfYSpawn: 50
  ironGenerating: 10
  gcoins:
    kill: 3
    win: 10
    capture: 10
  coins:
    kill: 5
    win: 20
    capture: 10
  xp:
    kill: 5
    win: 10
    capture: 10
  noDrop:
    - WOOL
    - DIAMOND_CHESTPLATE
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - GOLDEN_APPLE
bounty:
  min: 90
  max: 110
  perKill: 0.10
chat:
  joinMessage: true
  broadcastGame: true
items:
  lobby:
    enabled: true
    slot: 4
    cmd: /perfil
  lobby2:
    enabled: true
    slot: 0
    cmd: /ctw join
materials:
  lobby: DIAMOND
  closeitem: BOOK
win-commands:
  enabled: false
  cmds:
    - "say <player> is a pro!"
level-commands:
  enabled: false
  cmds:
    - "say <player> level up!"
death-commands:
  enabled: false
  cmds:
    - "say <player> is a noob!"
kill-commands:
  enabled: false
  cmds:
    - "say <player> is a killer!"
whitelistedCMD:
  - /leave
  - /msg
  - /stats
  - /join
  - /tell